#!/bin/sh

# Set these paths appropriately

BIN=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/bin
CMD=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/cmd
LIB=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup-greek.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/greek.par

$TOKENIZER $* |
# recognition of MWLs
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

