#!/bin/sh

# Set these paths appropriately

BIN=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/bin
CMD=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/cmd
LIB=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
