#!/bin/sh

# Set these paths appropriately

BIN=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/bin
CMD=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/cmd
LIB=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/spanish-abbreviations
PARFILE=${LIB}/spanish.par
MWLFILE=${LIB}/spanish-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

