#!/bin/sh

# Set these paths appropriately

BIN=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/bin
CMD=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/cmd
LIB=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/lib

OPTIONS="-token -lemma -sgml -pt-with-lemma"

TOKENIZER=${CMD}/tokenize.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/german-abbreviations
PARFILE=${LIB}/german.par
LEXFILE=${LIB}/german-lexicon.txt
FILTER=${CMD}/filter-german-tags

$TOKENIZER -a $ABBR_LIST $* |
# external lexicon lookup
perl $CMD/lookup.perl $LEXFILE |
# tagging
$TAGGER $OPTIONS $PARFILE  | 
# error correction
$FILTER
