#!/bin/sh

# Set these paths appropriately

BIN=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/bin
CMD=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/cmd
LIB=/home/l/tuandn/tarsqi/ttk-1.0/ttk-1.0/code/components/preprocessing/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
